spring.application.name=permis

app.frontend.url=https://permisduperenoel.fr

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api

# =========================================================
# STRIPE
# =========================================================
# Clé secrète Stripe
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret= ${STRIPE_WEBHOOK_SECRET}

# =========================================================
# MAIL (Brevo SMTP / Production)
# =========================================================
brevo.api.key=${BREVO_API_KEY}
spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
app.mail.from=${APP_MAIL_FROM}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000