spring.application.name=permis

app.frontend.url=http://localhost:5173

spring.datasource.url=jdbc:postgresql://localhost:5432/santa
spring.datasource.username=postgres
spring.datasource.password=Djaltek30

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/api

# =========================================================
# STRIPE
# =========================================================
# Clé secrète Stripe
stripe.api.key=sk_test_51UMruRFO6t2NzdTNTxnU2GKUW4ROOOBTgWHj66ANX9I5Th9fDi5zOqrmKCzfGPO7KcHtuP2OtUdPybZyjdV4Jv7H00a4J16HZw
# stripe.price.id=price_1UECW7F7hudVg9FELwKh64WR
stripe.webhook.secret= whsec_e903e70db7a12299f43ebd084a953b8cba25865244c3b5dbe389da12409dd7eb